services:
  healthchecker-1:
    container_name: healthchecker-1
    image: healthchecker:latest
    env_file:
      ./configs/env/healthchecker-1.env
    networks:
      - tp1_net
    volumes:
      - ./configs/healthchecker.toml:/app/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  tp1_net:
    external: false
