services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "15672:15672"
    networks:
      - tp1_net
    logging:
      driver: none

  gateway:
    container_name: gateway
    image: gateway:latest
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      tp1_net:
        ipv4_address: 172.25.125.100
    volumes:
      - ./configs/gateway.toml:/app/config.toml

  action-filter-1:
    container_name: action-filter-1
    image: action-filter:latest
    environment:
      - worker-id=0
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/action.json:/app/config.json

  joiner-counter-filter-1:
    container_name: joiner-counter-filter-1
    image: joiner-counter-filter:latest
    environment:
      - worker-id=0
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/joiner_counter.json:/app/config.json

  review-text-filter-1:
    container_name: review-text-filter-1
    image: review-text-filter:latest
    environment:
      - worker-id=0
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/text.json:/app/config.json

  reviews-filter-1:
    container_name: reviews-filter-1
    image: reviews-filter:latest
    environment:
      - worker-id=0
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/review.json:/app/config.json


  review-counter-agg:
    container_name: review-counter-agg
    image: counter:latest
    environment:
      - worker-id=0
    depends_on:
      - gateway
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/counter_agg.json:/app/config.json

networks:
  tp1_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24