services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "15672:15672"
    networks:
      - tp1_net
    logging:
      driver: none

  gateway:
    container_name: gateway
    image: gateway:latest
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      tp1_net:
        ipv4_address: 172.25.125.10

  top-5-filter:
    container_name: top-5-filter
    image: topn:latest
    environment:
      - worker-id=1 #????
    depends_on: #TODO
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - tp1_net

networks:
  tp1_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24