services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "15672:15672"
    networks:
      - tp1_net
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s
    logging:
      driver: none

  gateway-1:
    container_name: gateway-1
    image: gateway:latest
    environment:
      - worker-id=0
      - worker-uuid=gateway-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/gateway.toml:/app/config.toml
      - ./volumes/gateway-1.csv:/app/recovery.csv
      - ./volumes/id-generator-1.csv:/app/pkg/utils/id_generator/id-generator-1.csv

  reviews-filter-1:
    container_name: reviews-filter-1
    image: reviews-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=reviews-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/review.json:/app/config.json
      - ./volumes/reviews-filter-1.csv:/app/recovery.csv

  review-text-filter-1:
    container_name: review-text-filter-1
    image: review-text-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=review-text-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/text.json:/app/config.json
      - ./volumes/review-text-filter-1.csv:/app/recovery.csv

  review-text-filter-2:
    container_name: review-text-filter-2
    image: review-text-filter:latest
    environment:
      - worker-id=1
      - worker-uuid=review-text-filter-2
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/text.json:/app/config.json
      - ./volumes/review-text-filter-2.csv:/app/recovery.csv

  review-text-filter-3:
    container_name: review-text-filter-3
    image: review-text-filter:latest
    environment:
      - worker-id=2
      - worker-uuid=review-text-filter-3
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/text.json:/app/config.json
      - ./volumes/review-text-filter-3.csv:/app/recovery.csv

  review-text-filter-4:
    container_name: review-text-filter-4
    image: review-text-filter:latest
    environment:
      - worker-id=3
      - worker-uuid=review-text-filter-4
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/text.json:/app/config.json
      - ./volumes/review-text-filter-4.csv:/app/recovery.csv

  review-text-filter-5:
    container_name: review-text-filter-5
    image: review-text-filter:latest
    environment:
      - worker-id=4
      - worker-uuid=review-text-filter-5
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/text.json:/app/config.json
      - ./volumes/review-text-filter-5.csv:/app/recovery.csv

  action-filter-1:
    container_name: action-filter-1
    image: action-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=action-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/action.json:/app/config.json
      - ./volumes/action-filter-1.csv:/app/recovery.csv

  indie-filter-1:
    container_name: indie-filter-1
    image: indie-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=indie-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/indie.json:/app/config.json
      - ./volumes/indie-filter-1.csv:/app/recovery.csv

  platform-filter-1:
    container_name: platform-filter-1
    image: platform-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=platform-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - gateway-1
    networks:
      - tp1_net
    volumes:
      - ./configs/platform.json:/app/config.json
      - ./volumes/platform-filter-1.csv:/app/recovery.csv

  joiner-counter-filter-1:
    container_name: joiner-counter-filter-1
    image: joiner-counter-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=joiner-counter-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/joiner_counter.json:/app/config.json
      - ./volumes/joiner-counter-filter-1.csv:/app/recovery.csv

  joiner-counter-filter-2:
    container_name: joiner-counter-filter-2
    image: joiner-counter-filter:latest
    environment:
      - worker-id=1
      - worker-uuid=joiner-counter-filter-2
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/joiner_counter.json:/app/config.json
      - ./volumes/joiner-counter-filter-2.csv:/app/recovery.csv

  joiner-top-filter-1:
    container_name: joiner-top-filter-1
    image: joiner-top-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=joiner-top-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/joiner_top.json:/app/config.json
      - ./volumes/joiner-top-filter-1.csv:/app/recovery.csv

  joiner-top-filter-2:
    container_name: joiner-top-filter-2
    image: joiner-top-filter:latest
    environment:
      - worker-id=1
      - worker-uuid=joiner-top-filter-2
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/joiner_top.json:/app/config.json
      - ./volumes/joiner-top-filter-2.csv:/app/recovery.csv

  joiner-percentile-filter-1:
    container_name: joiner-percentile-filter-1
    image: joiner-percentile-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=joiner-percentile-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/joiner_percentile.json:/app/config.json
      - ./volumes/joiner-percentile-filter-1.csv:/app/recovery.csv

  joiner-percentile-filter-2:
    container_name: joiner-percentile-filter-2
    image: joiner-percentile-filter:latest
    environment:
      - worker-id=1
      - worker-uuid=joiner-percentile-filter-2
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/joiner_percentile.json:/app/config.json
      - ./volumes/joiner-percentile-filter-2.csv:/app/recovery.csv

  percentile-filter-1:
    container_name: percentile-filter-1
    image: percentile:latest
    environment:
      - worker-id=0
      - worker-uuid=percentile-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/percentile.json:/app/config.json
      - ./volumes/percentile-filter-1.csv:/app/recovery.csv

  topn-filter-1:
    container_name: topn-filter-1
    image: topn:latest
    environment:
      - worker-id=0
      - worker-uuid=topn-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/topn.json:/app/config.json
      - ./volumes/topn-filter-1.csv:/app/recovery.csv

  topn-filter-2:
    container_name: topn-filter-2
    image: topn:latest
    environment:
      - worker-id=1
      - worker-uuid=topn-filter-2
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/topn.json:/app/config.json
      - ./volumes/topn-filter-2.csv:/app/recovery.csv

  topn-aggregator-1:
    container_name: topn-aggregator-1
    image: topn:latest
    environment:
      - worker-id=0
      - worker-uuid=topn-aggregator-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/topn_agg.json:/app/config.json
      - ./volumes/topn-aggregator-1.csv:/app/recovery.csv

  platform-counter-1:
    container_name: platform-counter-1
    image: platform-counter:latest
    environment:
      - worker-id=0
      - worker-uuid=platform-counter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/platform_counter.json:/app/config.json
      - ./volumes/platform-counter-1.csv:/app/recovery.csv

  platform-aggregator-1:
    container_name: platform-aggregator-1
    image: platform-counter:latest
    environment:
      - worker-id=0
      - worker-uuid=platform-aggregator-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/platform_counter_agg.json:/app/config.json
      - ./volumes/platform-aggregator-1.csv:/app/recovery.csv

  topn-playtime-filter-1:
    container_name: topn-playtime-filter-1
    image: topn-playtime-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=topn-playtime-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/topn_playtime.json:/app/config.json
      - ./volumes/topn-playtime-filter-1.csv:/app/recovery.csv

  release-date-filter-1:
    container_name: release-date-filter-1
    image: release-date-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=release-date-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/release_date.json:/app/config.json
      - ./volumes/release-date-filter-1.csv:/app/recovery.csv

  topn-playtime-aggregator-1:
    container_name: topn-playtime-aggregator-1
    image: topn-playtime-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=topn-playtime-aggregator-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/topn_playtime_agg.json:/app/config.json
      - ./volumes/topn-playtime-aggregator-1.csv:/app/recovery.csv

  review-counter-agg:
    container_name: review-counter-agg
    image: counter:latest
    environment:
      - worker-id=0
      - worker-uuid=review-counter-agg
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/counter_agg.json:/app/config.json
      - ./volumes/review-counter-agg.csv:/app/recovery.csv

networks:
  tp1_net:
    external: false
