services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "15672:15672"
    networks:
      - tp1_net
    logging:
      driver: none

  gateway:
    container_name: gateway
    image: gateway:latest
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      tp1_net:
        ipv4_address: 172.25.125.100
    volumes:
      - ./configs/gateway.toml:/app/config.toml


networks:
  tp1_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24