services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "15672:15672"
    networks:
      - tp1_net
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s
    logging:
      driver: none

  gateway-1:
    container_name: gateway-1
    image: gateway:latest
    environment:
      - worker-id=0
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/gateway.toml:/app/config.toml

  health-checker-1:
    container_name: health-checker-1
    image: healthchecker:latest
    env_file:
      ./configs/health-checker-1.env
    networks:
      - tp1_net
    volumes:
      - ./configs/health_checker.toml:/app/config.toml
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  tp1_net:
    external: false
