services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "15672:15672"
    networks:
      - tp1_net
    logging:
      driver: none

  gateway:
    container_name: gateway
    image: gateway:latest
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      tp1_net:
        ipv4_address: 172.25.125.100
    volumes:
      - ./configs/gateway.toml:/app/config.toml

  platform-filter-1:
    container_name: platform-filter-1
    image: platform-filter:latest
    environment:
      - worker-id=0
    depends_on:
      - rabbitmq
    links:
      - gateway
    networks:
      - tp1_net
    volumes:
      - ./configs/platform.json:/app/config.json

  platform-counter-1:
    container_name: platform-counter-1
    image: platform-counter:latest
    environment:
      - worker-id=0
    depends_on:
      - gateway
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/platform_counter.json:/app/config.json

  platform-aggregator-1:
    container_name: platform-aggregator-1
    image: platform-counter:latest
    environment:
      - worker-id=0
    depends_on:
      - gateway
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/platform_counter_agg.json:/app/config.json

networks:
  tp1_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24