services:
  client:
    container_name: client
    image: client:latest
    volumes:
      - ./data:/app/data
      - ./configs/client.toml:/app/config.toml
    networks:
      - tp1_net
networks:
  tp1_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24