services:
  client-1:
    container_name: client-1
    image: client:latest
    volumes:
      - ./data:/app/data
      - ./configs/client.toml:/app/config.toml
    networks:
      - tp1_net

  client-2:
    container_name: client-2
    image: client:latest
    volumes:
      - ./data:/app/data
      - ./configs/client.toml:/app/config.toml
    networks:
      - tp1_net

  client-3:
    container_name: client-3
    image: client:latest
    volumes:
      - ./data:/app/data
      - ./configs/client.toml:/app/config.toml
    networks:
      - tp1_net

networks:
  tp1_net:
    external: false
