services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "15672:15672"
    networks:
      - tp1_net
    logging:
      driver: none

  gateway:
    container_name: gateway
    image: gateway:latest
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      tp1_net:
        ipv4_address: 172.25.125.100
    volumes:
      - ./configs/gateway.toml:/app/config.toml

  reviews-filter-1:
    container_name: reviews-filter-1
    image: reviews-filter:latest
    environment:
      - worker-id=0
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/review.json:/app/config.json

  indie-filter-1:
    container_name: indie-filter-1
    image: indie-filter:latest
    environment:
      - worker-id=0
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/indie.json:/app/config.json

  joiner-top-filter-1:
    container_name: joiner-top-filter-1
    image: joiner-top-filter:latest
    environment:
      - worker-id=0
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/joiner_top.json:/app/config.json

  topn-filter-1:
    container_name: topn-filter-1
    image: topn:latest
    environment:
      - worker-id=0
    depends_on:
      - gateway
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/topn.json:/app/config.json

  topn-aggregator-1:
    container_name: topn-aggregator-1
    image: topn:latest
    environment:
      - worker-id=0
    depends_on:
      - gateway
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/topn_agg.json:/app/config.json

networks:
  tp1_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24