services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "15672:15672"

  reviews-filter-1:
    container_name: reviews-filter-1
    image: reviews-filter:latest
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
