services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "15672:15672"

  gateway:
    container_name: gateway
    image: gateway:latest
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

