services:
  health-checker-1:
    container_name: health-checker-1
    image: healthchecker:latest
    env_file:
      ./configs/health-checker-1.env
    networks:
      - tp1_net
    volumes:
      - ./configs/health_checker.toml:/app/config.toml
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  tp1_net:
    external: false
