services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "15672:15672"
    networks:
      - tp1_net
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s
    logging:
      driver: none

  gateway-1:
    container_name: gateway-1
    image: gateway:latest
    environment:
      - worker-id=0
      - worker-uuid=gateway-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/gateway.toml:/config.toml
      - ./volumes/gateway-1:/recovery
      - ./volumes/id-generator-1.csv:/pkg/utils/id/id-generator-1.csv

  reviews-filter-1:
    container_name: reviews-filter-1
    image: reviews-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=reviews-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/review.json:/config.json
      - ./volumes/reviews-filter-1:/recovery

  review-text-filter-1:
    container_name: review-text-filter-1
    image: review-text-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=review-text-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/text.json:/config.json
      - ./volumes/review-text-filter-1:/recovery

  review-text-filter-2:
    container_name: review-text-filter-2
    image: review-text-filter:latest
    environment:
      - worker-id=1
      - worker-uuid=review-text-filter-2
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/text.json:/config.json
      - ./volumes/review-text-filter-2:/recovery

  review-text-filter-3:
    container_name: review-text-filter-3
    image: review-text-filter:latest
    environment:
      - worker-id=2
      - worker-uuid=review-text-filter-3
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/text.json:/config.json
      - ./volumes/review-text-filter-3:/recovery

  review-text-filter-4:
    container_name: review-text-filter-4
    image: review-text-filter:latest
    environment:
      - worker-id=3
      - worker-uuid=review-text-filter-4
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/text.json:/config.json
      - ./volumes/review-text-filter-4:/recovery

  review-text-filter-5:
    container_name: review-text-filter-5
    image: review-text-filter:latest
    environment:
      - worker-id=4
      - worker-uuid=review-text-filter-5
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/text.json:/config.json
      - ./volumes/review-text-filter-5:/recovery

  action-filter-1:
    container_name: action-filter-1
    image: action-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=action-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/action.json:/config.json
      - ./volumes/action-filter-1:/recovery

  indie-filter-1:
    container_name: indie-filter-1
    image: indie-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=indie-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/indie.json:/config.json
      - ./volumes/indie-filter-1:/recovery

  platform-filter-1:
    container_name: platform-filter-1
    image: platform-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=platform-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - gateway-1
    networks:
      - tp1_net
    volumes:
      - ./configs/platform.json:/config.json
      - ./volumes/platform-filter-1:/recovery

  counter-joiner-1:
    container_name: counter-joiner-1
    image: counter-joiner:latest
    environment:
      - worker-id=0
      - worker-uuid=counter-joiner-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/joiner_counter.json:/config.json
      - ./volumes/counter-joiner-1:/recovery

  counter-joiner-2:
    container_name: counter-joiner-2
    image: counter-joiner:latest
    environment:
      - worker-id=1
      - worker-uuid=counter-joiner-2
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/joiner_counter.json:/config.json
      - ./volumes/counter-joiner-2:/recovery

  top-joiner-1:
    container_name: top-joiner-1
    image: top-joiner:latest
    environment:
      - worker-id=0
      - worker-uuid=top-joiner-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/joiner_top.json:/config.json
      - ./volumes/top-joiner-1:/recovery

  top-joiner-2:
    container_name: top-joiner-2
    image: top-joiner:latest
    environment:
      - worker-id=1
      - worker-uuid=top-joiner-2
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/joiner_top.json:/config.json
      - ./volumes/top-joiner-2:/recovery

  percentile-joiner-1:
    container_name: percentile-joiner-1
    image: percentile-joiner:latest
    environment:
      - worker-id=0
      - worker-uuid=percentile-joiner-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/joiner_percentile.json:/config.json
      - ./volumes/percentile-joiner-1:/recovery

  percentile-joiner-2:
    container_name: percentile-joiner-2
    image: percentile-joiner:latest
    environment:
      - worker-id=1
      - worker-uuid=percentile-joiner-2
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/joiner_percentile.json:/config.json
      - ./volumes/percentile-joiner-2:/recovery

  percentile-aggregator:
    container_name: percentile-aggregator
    image: percentile:latest
    environment:
      - worker-id=0
      - worker-uuid=percentile-aggregator
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/percentile.json:/config.json
      - ./volumes/percentile-aggregator:/recovery

  topn-filter-1:
    container_name: topn-filter-1
    image: topn:latest
    environment:
      - worker-id=0
      - worker-uuid=topn-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/topn.json:/config.json
      - ./volumes/topn-filter-1:/recovery

  topn-filter-2:
    container_name: topn-filter-2
    image: topn:latest
    environment:
      - worker-id=1
      - worker-uuid=topn-filter-2
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/topn.json:/config.json
      - ./volumes/topn-filter-2:/recovery

  topn-aggregator:
    container_name: topn-aggregator
    image: topn:latest
    environment:
      - worker-id=0
      - worker-uuid=topn-aggregator
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/topn_agg.json:/config.json
      - ./volumes/topn-aggregator:/recovery

  platform-counter-1:
    container_name: platform-counter-1
    image: platform-counter:latest
    environment:
      - worker-id=0
      - worker-uuid=platform-counter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/platform_counter.json:/config.json
      - ./volumes/platform-counter-1:/recovery

  platform-aggregator:
    container_name: platform-aggregator
    image: platform-counter:latest
    environment:
      - worker-id=0
      - worker-uuid=platform-aggregator
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/platform_counter_agg.json:/config.json
      - ./volumes/platform-aggregator:/recovery

  topn-playtime-filter-1:
    container_name: topn-playtime-filter-1
    image: topn-playtime-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=topn-playtime-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/topn_playtime.json:/config.json
      - ./volumes/topn-playtime-filter-1:/recovery

  release-date-filter-1:
    container_name: release-date-filter-1
    image: release-date-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=release-date-filter-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/release_date.json:/config.json
      - ./volumes/release-date-filter-1:/recovery

  topn-playtime-aggregator:
    container_name: topn-playtime-aggregator
    image: topn-playtime-filter:latest
    environment:
      - worker-id=0
      - worker-uuid=topn-playtime-aggregator
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/topn_playtime_agg.json:/config.json
      - ./volumes/topn-playtime-aggregator:/recovery

  review-counter-aggregator:
    container_name: review-counter-aggregator
    image: counter:latest
    environment:
      - worker-id=0
      - worker-uuid=review-counter-aggregator
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    networks:
      - tp1_net
    volumes:
      - ./configs/counter_agg.json:/config.json
      - ./volumes/review-counter-aggregator:/recovery

networks:
  tp1_net:
    external: false
