services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "15672:15672"
    networks:
      - tp1_net
    logging:
      driver: none

  gateway:
    container_name: gateway
    image: gateway:latest
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      tp1_net:
        ipv4_address: 172.25.125.10

  reviews-filter-1:
    container_name: reviews-filter-1
    image: reviews-filter:latest
    environment:
      - worker-id=0
    depends_on:
      - rabbitmq
      - gateway
    links:
      - rabbitmq
    networks:
      - tp1_net

  review-text-filter-1:
    container_name: review-text-filter-1
    image: review-text-filter:latest
    environment:
      - worker-id=0
    depends_on:
      - gateway
    links:
      - rabbitmq
    networks:
      - tp1_net

  action-filter-1:
    container_name: action-filter-1
    image: action-filter:latest
    environment:
      - worker-id=0
    depends_on:
      - gateway
    links:
      - rabbitmq
    networks:
      - tp1_net

  indie-filter-1:
    container_name: indie-filter-1
    image: indie-filter:latest
    environment:
      - worker-id=0
    depends_on:
      - gateway
    links:
      - rabbitmq
    networks:
      - tp1_net

  platform-filter-1:
    container_name: platform-filter-1
    image: platform-filter:latest
    environment:
      - worker-id=0
    depends_on:
      - gateway
    links:
      - rabbitmq
    networks:
      - tp1_net

networks:
  tp1_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24