[gateway]
address = "172.25.125.100"
reviews_port = 5050
games_port = 5051
results_port = 5052
ids_port = 5053

[client]
games_path = "data/games.csv"
reviews_path = "data/reviews.csv"
max_messages = 5


