[gateway]
address = "gateway-1"
reviews_port = 5050
games_port = 5051
results_port = 5052
ids_port = 5053

[client]
games_path = "data/fafa_games.csv"
reviews_path = "data/fafa_reviews.csv"
max_messages = 5
timeout = 5
chunk_size = 100

