[gateway]
address = "gateway-1"
reviews_port = 5050
games_port = 5051
results_port = 5052
ids_port = 5053

[client]
games_path = "data/games_reduced.csv"
reviews_path = "data/reviews_reduced.csv"
max_messages = 5
