[gateway]
reviews-address = "172.25.125.100:5050"
games-address = "172.25.125.100:5051"
buffer_size = 16384
chunk_size = 10
log_level = "INFO"

[rabbitmq]
reviews_q = "reviews"
games_platform_q = "games_platform"
games_action_q = "games_action"
games_indie_q = "games_indie"
exchange_name = "gateway"
exchange_kind = "direct"
reviews_routing_key = "review"
games_routing_key = "game"


