[gateway]
reviews-address = "0.0.0.0:5050"
games-address = "0.0.0.0:5051"
results-address = "0.0.0.0:5052"
client-id-address = "0.0.0.0:5053"

buffer_size = 16384
chunk_size = 100
log_level = "INFO"

[rabbitmq]
exchange_name = "gateway"
exchange_kind = "direct"

[rabbitmq.reviews]
queue = "reviews_%d"
key = "reviews-%d"
consumers = 1
reviews_q = "reviews_%d"

[rabbitmq.action]
queue = "games_action_%d"
key = "games-action-%d"
consumers = 1

[rabbitmq.indie]
queue = "games_indie_%d"
key = "games-indie-%d"
consumers = 1

[rabbitmq.platform]
queue = "games_platform_%d"
key = "games-platform-%d"
consumers = 1

[rabbitmq.reports]
queue = "reports_%d"
