[gateway]
reviews-address = "0.0.0.0:5050"
games-address = "0.0.0.0:5051"
results-address = "0.0.0.0:5052"
client-id-address = "0.0.0.0:5053"

buffer_size = 16384
chunk_size = 100
log_level = "INFO"

[rabbitmq]
reviews_q = "reviews"
games_platform_q = "games_platform"
games_action_q = "games_action"
games_indie_q = "games_indie"
exchange_name = "gateway"
exchange_kind = "direct"
reviews_routing_key = "review"
games_routing_key = "game"
reports = "reports"


