[gateway]
address = "127.0.0.1:5050"
buffer_size = 1024
chunk_size = 100

[rabbitmq]
reviews_q = "reviews"
games_platform_q = "games_platform"
games_shooter_q = "games_shooter"
games_indie_q = "games_indie"
exchange_name = "gateway"
exchange_type = "direct"
reviews_routing_key = "review"
games_routing_key = "game"


