[query]
genre = "indie"

[gateway]
queue = "games_indie"
key = "input"

[exchange]
name = "indies"
kind = "direct"
peers = 1

[playtime-queue]
name = "indie_games"
key = ""

[positive-queue]
name = "query3_games_%d"
key = "%d"
consumers = 2
