[gateway]
exchange = "gateway"
queue = "reviews"
key = "review"

[log]
level = "INFO"

[exchange]
name = "reviews"
kind = "direct"
peers = 2

[positive-reviews]
queue-name = "positive_reviews"

[positive-reviews-sh]
consumers = 3
queue-name = "positive_reviews_%d"
key = "p%d"

[negative-reviews-sh]
consumers = 3
queue-name = "negative_reviews_%d"
key = "n%d"
